### ISSUE TITLE
我想问下广工大佬最后去了哪里

### ISSUE THREAD

**Issue by wenbochang888** [lewky/Seckill#1]
今年大三，准备春招
然后看了这个秒杀视频，面试的时候这个项目算拿的出手么？
谢谢
我隔壁的 广财

**Comment by lewky** [comment]
我只是个渣渣。。这个项目还是挺不错的，好好琢磨下视频，把项目做一遍，了解熟悉下知识点，去面试还是有帮助的，我有一次群面的题目就是和这个项目差不多的，讨论的是天猫双十一的高并发秒杀问题。
这个项目可以写到简历里，你是大三，春招的话找实习应该是有帮助的，记得多刷题，看看网上的一些面试题
