### ISSUE TITLE
我运行项目（只有dao层）时，发现c3p0依赖出错

### ISSUE THREAD

**Issue by kite3** [lewky/seckill#2]
（1）具体是这样的：我完全复制你的代码，进行单元测试时报错：
```
Failed to load ApplicationContext 以及 
Cannot find class [com.mchange.v2.c3p0.ComboPooledDataSource]
```

（2）后来发现是c3p0依赖不对，改为这个后每个方法测试都OK：

```
<dependency>
    <groupId>com.mchange</groupId>
    <artifactId>c3p0</artifactId>
    <version>0.9.5.2</version>
</dependency>
```

（3）我的开发环境：
操作系统：Windows 7
IDE工具：Eclipse 4.7
JDK：JDK 1.8
中间件：Tomcat 8.5
数据库：MySQL 5.7
构建工具：Maven 3.5.2
框架：SSM

**Comment by lewky** [comment]
按照项目中的配置，我可以单元测试成功，查看了下0.9.1.1版本的c3p0的jar包，也存在着ComboPooledDataSource这个类，所以你的问题我也不清楚为什么，至少在我的项目环境下是可以测试成功的。
